In [1]:
import pandas as pd

In [6]:
import numpy as np

In [2]:
path_="C:/Users/CD44/Desktop/GPLA/GPLA_excel_.xlsx"

In [3]:
df_ = pd.read_excel(path_) #reading database

In [4]:
df_.info()

<class 'pandas.DataFrame'>
RangeIndex: 4541 entries, 0 to 4540
Columns: 255 entries, Numéro d'inventaire to Institution / Département
dtypes: datetime64[us](4), float64(10), object(11), str(230)
memory usage: 11.7+ MB

In [8]:
df_.shape

(4541, 255)

In [9]:
df_.head(25)

,Numéro d'inventaire,Numéro de dépôt,Numéro d'inventaire du déposant,Autre numéro,Autre numéro_2,Autre numéro_3,Autre numéro_4,Autre numéro_5,Autre numéro_6,Désignation du bien,...,Etat_4,Intégrité_4.1,Intégrité_4_2,Intégrité_4_3,Date du constat_4,Dégradation_4.1,Multimédia_4,Notice créée le,Notice modifiée le,Institution / Département
0,09/ S.INV,NaN,NaN,N° système v6 : 73425,NaN,NaN,NaN,NaN,NaN,fragment non déterminé,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 22 juillet 2002 10:15:52,mardi 16 mai 2017 12:54:07,Archéologie militaire/Militaria
1,13/ S.INV,NaN,NaN,N° système v6 : 73429,NaN,NaN,NaN,NaN,NaN,obusier,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 22 juillet 2002 10:38:33,jeudi 24 juin 2021 08:26:23,Archéologie militaire/Militaria
2,14/ S.INV,NaN,NaN,N° système v6 : 73430,NaN,NaN,NaN,NaN,NaN,obus (paire),...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 22 juillet 2002 11:02:32,vendredi 17 octobre 2014 10:47:08,Archéologie militaire/Militaria
3,20/ S.INV,NaN,NaN,N° système v6 : 73437,NaN,NaN,NaN,NaN,NaN,épée de ville,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 22 juillet 2002 11:30:05,lundi 27 octobre 2014 10:51:49,Archéologie militaire/Militaria
4,22/ S.INV,NaN,NaN,N° système v6 : 73439,NaN,NaN,NaN,NaN,NaN,fourreau d'épée,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 22 juillet 2002 11:34:21,lundi 27 octobre 2014 12:52:37,Archéologie militaire/Militaria
5,38/ S.INV,NaN,NaN,N° système v6 : 73417,NaN,NaN,NaN,NaN,NaN,czapka,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 22 juillet 2002 09:47:21,mercredi 5 mai 2021 10:41:01,Archéologie militaire/Militaria
6,56.614,NaN,NaN,N° système v6 : 8673,NaN,NaN,NaN,NaN,NaN,manche,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,vendredi 9 janvier 2015 17:24:59,Archéologie militaire/Militaria
7,56.841,NaN,NaN,N° système v6 : 8882,NaN,NaN,NaN,NaN,NaN,clef,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,vendredi 9 juillet 2010 16:35:51,Archéologie
8,56.842,NaN,NaN,N° système v6 : 8883,NaN,NaN,NaN,NaN,NaN,clef,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,lundi 3 septembre 2012 14:13:51,Archéologie
9,56.843,NaN,NaN,N° système v6 : 8884,NaN,NaN,NaN,NaN,NaN,clef,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mardi 20 septembre 2016 08:29:59,Archéologie
10,56.844,NaN,NaN,N° système v6 : 8885,NaN,NaN,NaN,NaN,NaN,clef,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,lundi 3 septembre 2012 14:17:29,Archéologie
11,56.845,NaN,NaN,N° système v6 : 8886,NaN,NaN,NaN,NaN,NaN,clef,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mercredi 29 août 2012 15:27:06,Archéologie
12,56.847,NaN,NaN,N° système v6 : 8888,NaN,NaN,NaN,NaN,NaN,clef,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,lundi 3 septembre 2012 14:20:18,Archéologie
13,56.848,NaN,NaN,N° système v6 : 8889,NaN,NaN,NaN,NaN,NaN,boucle,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,vendredi 24 janvier 2025 17:34:14,Archéologie
14,56.849,NaN,NaN,N° système v6 : 8890,NaN,NaN,NaN,NaN,NaN,boucle,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mardi 2 avril 2019 09:06:43,Archéologie
15,56.861,NaN,NaN,N° système v6 : 8902,NaN,NaN,NaN,NaN,NaN,bracelet,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mercredi 15 janvier 2025 14:59:11,Archéologie
16,56.862,NaN,NaN,N° système v6 : 8406,NaN,NaN,NaN,NaN,NaN,bracelet,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mardi 2 juin 2020 14:32:07,Archéologie
17,56.863,NaN,NaN,N° système v6 : 8903,NaN,NaN,NaN,NaN,NaN,bracelet,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,jeudi 18 août 2011 16:47:59,Archéologie
18,56.865,NaN,NaN,N° système v6 : 8905,NaN,NaN,NaN,NaN,NaN,anneau,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mercredi 6 juillet 2011 15:16:25,Archéologie
19,56.866,NaN,NaN,N° système v6 : 8906,NaN,NaN,NaN,NaN,NaN,anneau,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mercredi 6 juillet 2011 15:20:49,Archéologie
20,56.867,NaN,NaN,N° système v6 : 8907,NaN,NaN,NaN,NaN,NaN,anneau,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mercredi 6 juillet 2011 15:26:19,Archéologie
21,56.868,NaN,NaN,N° système v6 : 8908,NaN,NaN,NaN,NaN,NaN,anneau,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mercredi 6 juillet 2011 10:20:07,Archéologie
22,56.870,NaN,NaN,N° système v6 : 8910,NaN,NaN,NaN,NaN,NaN,fibule,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mercredi 19 septembre 2012 11:02:51,Archéologie
23,56.871,NaN,NaN,N° système v6 : 8911,NaN,NaN,NaN,NaN,NaN,fibule,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,jeudi 25 février 2021 14:32:44,Archéologie
24,56.872,NaN,NaN,N° système v6 : 8912,NaN,NaN,NaN,NaN,NaN,fibule,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,vendredi 13 décembre 1996 00:00:00,mercredi 24 février 2021 12:21:21,Archéologie

In [10]:
df_filtre = df_[df_["Numéro d'inventaire"].isna() | (df_["Numéro d'inventaire"] == "")]

In [11]:
df_filtre

,Numéro d'inventaire,Numéro de dépôt,Numéro d'inventaire du déposant,Autre numéro,Autre numéro_2,Autre numéro_3,Autre numéro_4,Autre numéro_5,Autre numéro_6,Désignation du bien,...,Etat_4,Intégrité_4.1,Intégrité_4_2,Intégrité_4_3,Date du constat_4,Dégradation_4.1,Multimédia_4,Notice créée le,Notice modifiée le,Institution / Département
4353,NaN,D 960.1.1,NaN,N° système v6 : 29225,NaN,NaN,NaN,NaN,NaN,plaque-boucle,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,mercredi 20 mai 1998 00:00:00,mardi 2 avril 2019 09:14:42,Archéologie
4354,NaN,D 960.1.2,NaN,N° système v6 : 29227,NaN,NaN,NaN,NaN,NaN,plaque-boucle (fragment),...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,mercredi 20 mai 1998 00:00:00,mardi 2 avril 2019 09:14:43,Archéologie
4355,NaN,D 960.1.3,NaN,N° système v6 : 29229,NaN,NaN,NaN,NaN,NaN,plaque-boucle (fragment),...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,mercredi 20 mai 1998 00:00:00,jeudi 27 juillet 2023 16:16:56,Archéologie
4356,NaN,D 960.1.4,NaN,N° système v6 : 29231,NaN,NaN,NaN,NaN,NaN,plaque-boucle (fragment),...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,mercredi 20 mai 1998 00:00:00,vendredi 24 janvier 2025 17:36:05,Archéologie
4357,NaN,D 960.1.5,NaN,N° système v6 : 29233,NaN,NaN,NaN,NaN,NaN,boucle,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,mercredi 20 mai 1998 00:00:00,mardi 2 avril 2019 09:14:46,Archéologie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4536,NaN,D 2004.2.1 (restitué),NaN,N° système v6 : 79798,NaN,NaN,NaN,NaN,NaN,figurine,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,mercredi 16 juin 2004 09:39:41,jeudi 26 septembre 2024 16:07:42,Archéologie
4537,NaN,D 2010.2.12,NaN,N° système v6 : 92233,NaN,NaN,NaN,NaN,NaN,épée,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 15 juin 2015 17:22:52,jeudi 22 avril 2021 15:01:29,Archéologie
4538,NaN,D 2019.3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,poignard,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 9 mars 2020 16:47:03,mercredi 11 janvier 2023 12:47:11,Archéologie
4539,NaN,D 2022.2.2,MT 1267.0003,NaN,NaN,NaN,NaN,NaN,NaN,manche de couteau,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,lundi 5 décembre 2022 12:26:05,mercredi 15 janvier 2025 18:19:39,Archéologie
4540,NaN,SRA 089,NaN,n° fouille : 44.094.002.AH_1974.501_M.MT...,N° système v6 : 81177,NaN,NaN,NaN,NaN,instrument de chirurgie,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,jeudi 16 mars 2006 10:15:41,jeudi 4 octobre 2018 12:08:51,Archéologie

In [17]:
df_filtre.to_excel("lignes_x_vide_GPLA.xlsx", index=False)

In [12]:
path="C:/Users/CD44/Desktop/Narval/narvalentier.xlsx"
df = pd.read_excel(path) #reading database

In [14]:
df

,id,nom_objet,numero_dossier,demandeur,nom_institution,site,date_entree,date_sortie,numero_inventaire_interne,datation_objet,...,typologie_objet,date_restitution_photos,date_restitution_fiche_restauration,id_dossier,version,numero_fiche,date_modification,nb_reference,matricule,localisation
0,102037,chaussure gauche,00000001,mr chausson,musée de la charentaise,NaN,2019-06-21,NaN,000001,20 ans,...,NaN,NaN,NaN,4426.0,9,000000001,2024-01-09 11:34:14.35,25.0,010393W,NaN
1,102039,chaussure gauche,00000001,mr chausson,musée de la charentaise,NaN,2019-06-21,NaN,000001,20 ans,...,NaN,NaN,NaN,4426.0,2,0000002,2024-01-09 11:34:14.35,NaN,NaN,NaN
2,102038,chaussure gauche,00000001,mr chausson,musée de la charentaise,NaN,2019-06-21,NaN,000001,20 ans,...,NaN,NaN,NaN,4426.0,2,0000002,2024-01-09 11:34:14.35,NaN,NaN,NaN
3,102040,chaussure gauche,00000001,mr chausson,musée de la charentaise,NaN,2019-06-21,NaN,000004,20 ans,...,NaN,NaN,NaN,4426.0,2,000065,2024-01-09 11:34:14.35,NaN,NaN,NaN
4,100050,NaN,D124-747/98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3619.0,0,1313156,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15530,100052,NaN,D14-81/96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3621.0,0,test_objet,NaN,NaN,NaN,NaN
15531,100053,NaN,D26-114/95,NaN,NaN,NaN,2016-11-22,NaN,NaN,NaN,...,NaN,NaN,NaN,3623.0,1,test_objet,NaN,NaN,NaN,NaN
15532,102002,NaN,D229-360/17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4368.0,0,testsm,NaN,NaN,NaN,NaN
15533,102004,NaN,D231-362/17,NaN,NaN,NaN,2017-06-12,NaN,NaN,NaN,...,NaN,NaN,NaN,4370.0,1,testsm,NaN,NaN,NaN,NaN
15534,102045,NaN,D124-324/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4430.0,6,test-sm 2,2025-05-20 16:29:17.76,26.0,NaN,NaN

In [15]:
df_filtre_ = df[df["numero_inventaire_interne"].isna() | (df["numero_inventaire_interne"] == "")]

In [16]:
df_filtre_

,id,nom_objet,numero_dossier,demandeur,nom_institution,site,date_entree,date_sortie,numero_inventaire_interne,datation_objet,...,typologie_objet,date_restitution_photos,date_restitution_fiche_restauration,id_dossier,version,numero_fiche,date_modification,nb_reference,matricule,localisation
4,100050,NaN,D124-747/98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3619.0,0,1313156,NaN,NaN,NaN,NaN
15,12,Plaque-boucle et ardillon + élément de ceinture,D5/90,S.R.A. Pays de la Loire,NaN,Cheméré (Loire Atlantique) - 44 S.151 07.1989,1990-01-25,1990-05-10,NaN,Haut Moyen Age,...,'Plaque-boucle',NaN,NaN,3561.0,0,1990011,NaN,NaN,NaN,NaN
26,23,Couteau,D5/90,S.R.A. Pays de la Loire,NaN,Nantes - 44-108.014 AH Place du Commerce,1990-01-25,1990-05-10,NaN,NaN,...,NaN,NaN,NaN,3561.0,0,1990022,NaN,NaN,NaN,NaN
115,113,Monnaies (13),D8-98/91,Musée Dobrée (Nantes),Musée Dobrée (Nantes),NaN,1991-03-29,1991-04-09,NaN,NaN,...,'MONNAIE',NaN,NaN,3550.0,0,1991014,NaN,NaN,NaN,NaN
116,114,Monnaies (40),D8-98/91,Musée Dobrée (Nantes),Musée Dobrée (Nantes),NaN,1991-03-29,1991-04-09,NaN,NaN,...,'MONNAIE',NaN,NaN,3550.0,0,1991015,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15530,100052,NaN,D14-81/96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3621.0,0,test_objet,NaN,NaN,NaN,NaN
15531,100053,NaN,D26-114/95,NaN,NaN,NaN,2016-11-22,NaN,NaN,NaN,...,NaN,NaN,NaN,3623.0,1,test_objet,NaN,NaN,NaN,NaN
15532,102002,NaN,D229-360/17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4368.0,0,testsm,NaN,NaN,NaN,NaN
15533,102004,NaN,D231-362/17,NaN,NaN,NaN,2017-06-12,NaN,NaN,NaN,...,NaN,NaN,NaN,4370.0,1,testsm,NaN,NaN,NaN,NaN
15534,102045,NaN,D124-324/19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4430.0,6,test-sm 2,2025-05-20 16:29:17.76,26.0,NaN,NaN

In [18]:
df_filtre_.to_excel("lignes_x_vide_narval.xlsx", index=False)